syntax = "proto3";

package theater.v1;

import "google/protobuf/empty.proto";

service TheaterService {
    rpc ListTheaters (google.protobuf.Empty) returns (ListTheatersResponse);
    rpc GetTheater (GetTheaterRequest) returns (GetTheaterResponse);
    rpc CreateTheater (CreateTheaterRequest) returns (CreateTheaterResponse);
    rpc UpdateTheater (UpdateTheaterRequest) returns (UpdateTheaterResponse);
    rpc DeleteTheater (DeleteTheaterRequest) returns (DeleteTheaterResponse);
}

message ListTheatersResponse {
    repeated Theater theaters = 1;
}

message GetTheaterRequest {
    string id = 1;
}

message GetTheaterResponse {
    Theater theater = 1;
}

message CreateTheaterRequest {
    string name = 1;
    string address = 2;
}

message CreateTheaterResponse {
    Theater theater = 1;
}
message UpdateTheaterRequest {
    string id = 1;
    optional string name = 2;
    optional string address = 3;
}

message UpdateTheaterResponse {
    Theater theater = 1;
}

message DeleteTheaterRequest {
    string id = 1;
}

message DeleteTheaterResponse {
    bool ok = 1;
}

message Theater {
    string id = 1;
    string name = 2;
    string address = 3;
}